[package]
name = "rust_neural_network"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "performance_comparison"
harness = false
